name: 'CI'
on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - 'assigned'
      - 'opened'
      - 'synchronize'
      - 'reopened'
jobs:
  ci:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: 'Use Node.js 16.0'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '16.0'
      - name: 'Set up'
        run: |
          yarn install --frozen-lockfile
          yarn setup
      - name: 'Test'
        run: 'yarn test'
