name: 'CI'
on:
  pull_request:
    branches:
      - 'develop'
jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v3'
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: 'Use Node.js 18.0'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18.0'
      - name: 'Set up'
        run: |
          yarn install --frozen-lockfile
          yarn setup
      - name: 'Test'
        run: 'yarn test'
