name: 'CI'
on:
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:
jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v3'
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: 'Use Node.js 20.6'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '20.6'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jamashita'
      - name: 'Set up'
        run: 'yarn install --frozen-lockfile'
        env:
          NODE_AUTH_TOKEN: '${{ secrets.GPR_AUTH_TOKEN }}'
      - name: 'Check'
        run: 'yarn check'
      - name: 'Test'
        run: 'yarn test'
